---
- name: restart crio
  ansible.builtin.service:
    name: crio
    state: restarted
  become: true

- name: restart kubelet
  ansible.builtin.service:
    name: kubelet
    state: restarted
  become: true