# ==============================================================================
# [정적 인벤토리 템플릿 - Bastion 분리형 구조]
# Terraform에 의해 사설 IP와 Bastion 공인 IP가 주입됩니다.
# ==============================================================================

[masters]
k8s-master01 ansible_host=10.0.2.10
k8s-master02 ansible_host=10.0.2.11
k8s-master03 ansible_host=10.0.2.12

[workers]
k8s-worker01 ansible_host=10.0.2.21
k8s-worker02 ansible_host=10.0.2.22

[nfs]
k8s-nfs01 ansible_host=10.0.2.30

[lb]
k8s-lb01 ansible_host=10.0.2.110

[bastion]
bastion-host ansible_host=20.196.198.189

[all:vars]
ansible_user=azureuser
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3

ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes'

[masters:vars]
ansible_ssh_common_args='-o ProxyJump=azureuser@20.196.198.189 -o StrictHostKeyChecking=no -o ForwardAgent=yes'

[workers:vars]
ansible_ssh_common_args='-o ProxyJump=azureuser@20.196.198.189 -o StrictHostKeyChecking=no -o ForwardAgent=yes'

[nfs:vars]
ansible_ssh_common_args='-o ProxyJump=azureuser@20.196.198.189 -o StrictHostKeyChecking=no -o ForwardAgent=yes'

[lb:vars]
ansible_ssh_common_args='-o ProxyJump=azureuser@20.196.198.189 -o StrictHostKeyChecking=no -o ForwardAgent=yes'