apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRTBUa3R1Sk5qakV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeU1ERXhNekE1TVRoYUZ3MHpOVEV4TWpreE16RTBNVGhhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURZVzR4SVlqaUd6ZThpQUtCV2lNazduR2I3dXlZb2RoWS9CS3ZPSkJIZk9oUUUwcjU0WUJMUDR3Nk0KVEk2dEJnM0FIOFZQMmZDV0FiKzRNQ09qUmZqckhmekJ0RkpwenJkNjd0eFEwSTl4dHEwY2N2MGYxTkoxQzZUbQp4Skkxd29xb0lzMDhTdDdWc0tIdDljNElNNzlUNjY2TU1XTTlaRlBaK0dqOE1Tc202bjQ1eGxtU1ZycGNIZm1mCjJIYmI5WC9CVDNUSG9RVER6Si91OEYxZ0FSRVhKRlVkT1BpVHhUazdRL0lpOXZ5UCsydkQvTWROQ2cvZjNLT2kKYXRCWDdLMFdybURDWDI1YUE3NGEwVlpqUW81bHhUZ2VxY3l5ZXF4Rmppc3ZJTVFmUENNREozREZWTEx1ZGErVgozSElyUzIzamdiMS9aWWg3WDN6VXFYZVVFK05oQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUWVhIdGJOM2ZzMlRZNGU4eWZJWjhHMEwzUlREQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUtINTNZOTJ4QwpGeWJIVVowcDJGdWRHVmU3QWtLbGNYdkF1TG9nNkdSYk5Eb2NGODRzeXROWU8vK3U0UG1FSnMyaEFQbFpSRDdVCm9QMFVQUHNwbU1nRGI0YU5kNlBQK0V3WURrZDhsazcxcTkrUS9VUzFHb1VnTnB2Qi9mNHFrUU5WUXo0TWF3dXYKOTE1YWdXOWcySTlRSzhvZVlpeWxnM3J1ZFYwR29NRFM4dmxkeUtMMUsySHVVVWZtZU44TDNCejJzS3cwUHJYOAo3NXZXMktrK3VreGY1U1NoemdlNURxT2lMZWVJWFNrellQQ3RKaVJtaFdRNzNPc3VCV3dYTHF4dlo3K0VsTUJrCkFFQi9mSm1pcFdqRThFdkU5NENXcVBibDJQVDlkeGdkZU1Qd1c2elR1Qmp5SWpQRFZVaHM4SUFMNWE0UkNvYm4KMkxSdE8zUTBFR1V5Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://192.168.0.110:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: system:node:k8s-master01
  name: system:node:k8s-master01@kubernetes
current-context: system:node:k8s-master01@kubernetes
kind: Config
preferences: {}
users:
- name: system:node:k8s-master01
  user:
    client-certificate: /var/lib/kubelet/pki/kubelet-client-current.pem
    client-key: /var/lib/kubelet/pki/kubelet-client-current.pem
