apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infra-shared-storage-pvc
  namespace: nfs-provisioner
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
