- name: CNI - Calico 매니페스트 다운로드
  ansible.builtin.get_url:
    url: "{{ calico_manifest_url }}"
    dest: /tmp/calico.yaml
    mode: "0644"
  when: inventory_hostname == groups['masters'][0]

- name: CNI - Calico Pod CIDR 자동 치환
  ansible.builtin.shell: |
    sed -i 's@192.168.0.0/16@{{ pod_network_cidr }}@g' /tmp/calico.yaml
  when: inventory_hostname == groups['masters'][0]
  become: true

- name: CNI - Calico 적용
  ansible.builtin.shell: |
    # root 권한으로 admin.conf를 참조하여 실행
    kubectl apply -f /tmp/calico.yaml --kubeconfig=/etc/kubernetes/admin.conf
  when: inventory_hostname == groups['masters'][0]
  become: true
  register: cni_result
  until: cni_result.rc == 0
  retries: 5
  delay: 10