[masters]
k8s-master01 ansible_host=192.168.0.106
k8s-master02 ansible_host=192.168.0.107
k8s-master03 ansible_host=192.168.0.108

[workers]
k8s-worker01 ansible_host=192.168.0.111
k8s-worker02 ansible_host=192.168.0.112

[nfs]
nfs ansible_host=192.168.0.109

[lb]
lb-proxy ansible_host=192.168.0.110

[all:vars]
ansible_user=root

# ssh 키 경로
ansible_ssh_private_key_file=~/.ssh/id_ed25519

ansible_python_interpreter=/usr/bin/python3
