# 0) 공통 OS 설정 + 컨테이너 런타임 설치
- name: 모든 노드 공통 OS 준비 및 컨테이너 런타임 설치
  hosts: masters:workers:nfs:lb
  gather_facts: true
  become: true
  roles:
    - role: common
      tags: [common]
    - role: container_runtime
      tags: [runtime]
      when: "'masters' in group_names or 'workers' in group_names"

# 1) HAProxy 로드밸런서 서버 설정
- name: HAProxy LB 서버 설정
  hosts: lb
  gather_facts: true
  become: true
  roles:
    - role: lb
      tags: [lb]

# 2) 마스터 노드 설정
- name: 마스터 노드에 쿠버네티스 Control Plane 구성
  hosts: masters
  gather_facts: true 
  become: true
  roles:
    - role: master
      tags: [master]

# 3) CNI 설치
- name: CNI 플러그인 설치 (Calico 등)
  hosts: masters[0]
  gather_facts: false
  become: true
  roles:
    - role: cni
      tags: [cni]

# 4) 워커 노드 설정
- name: 워커 노드에 쿠버네티스 Worker 구성
  hosts: workers
  gather_facts: true 
  become: true
  roles:
    - role: worker
      tags: [worker]  

# 5) NFS 서버 설정
- name: NFS 서버 설정
  hosts: nfs
  gather_facts: true
  become: true
  roles:
    - role: nfs_server
      tags: [nfs]

# # 6) MetalLB 설정
# - name: 로드밸런서 서비스(MetalLB) 구성
#   hosts: masters[0]
#   gather_facts: true
#   become: true
#   roles:
#     - role: metallb
#       tags: [metallb] 