---
# 1. Join 여부 확인
- name: Worker - 기존 클러스터 Join 여부 확인
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: worker_kubelet_conf
  become: true

# 2. Join이 안 된 경우에만 패키지 설치 및 초기화 실행
- name: Worker - 패키지 설치 및 초기화 (Join 안 된 경우만)
  block:
    - name: Worker - 기존 흔적 제거
      ansible.builtin.shell: |
        kubeadm reset -f
        systemctl stop kubelet
        rm -rf /etc/kubernetes/
      become: true

    - name: Worker - 패키지 설치 (Ubuntu)
      ansible.builtin.apt:
        name: [kubeadm, kubelet, kubectl]
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
      become: true
  when: not worker_kubelet_conf.stat.exists

# 3. [핵심] 마스터에서 공유한 Join 명령어 가져오기
- name: Worker - 클러스터에 join 실행
  ansible.builtin.shell: >
    {{ hostvars[groups['masters'][0]]['kubernetes_join_command'] }}
    --cri-socket unix:///var/run/crio/crio.sock
    --ignore-preflight-errors=all
  when:
    - not worker_kubelet_conf.stat.exists
    - hostvars[groups['masters'][0]]['kubernetes_join_command'] is defined
  become: true

- name: Worker - kubelet 서비스 시작 및 활성화
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: true
  become: true